/* SERAY account panel. Same-origin BFF + HttpOnly sessions. No credentials in this file. */
(()=>{'use strict';
const $=id=>document.getElementById(id),endpoint='/.netlify/functions/seray-api';
const keys=['account','refresh','logout','setup','login','signup','recover','email','password','passwordNote','oneAccount','accountNote','orders','wallet','support','settings','admin','newOrder','amount','reference','topupNote','requestTopup','topups','transactions','subject','message','sendTicket','newPassword','repeatPassword','save','confirmOrder','debitNote','cancel','confirmPay','empty','done','failed','verify','resetSent','loading','paymentMissing','pending','approved','rejected','queued','processing','completed','partial','cancelled','needs_review','open','answered','closed','order','topup','refund','paidOrder','loginFirst','unavailable','insufficient','priceChanged','invalidLink','invalidQuantity','passwordMismatch','rates','service','rate','unit','min','max','enabled','providerId','providerType','manual','approve','reject','reply','users','block','unblock','sendProvider','sync','providerReview','reconcile','providerActualId','providerCatalog','providerMissing','range','charge','noPrices','signinError'];
const packs={
en:['My account','Refresh','Sign out','The account panel is being connected. You can still request a quote above.','Sign in','Create account','Reset password','Email','Password','Use at least 12 characters. Never share your social account password.','One account. Your orders in one place.','View orders, check your balance and contact support. Confirm your email before signing in. Your social account password is never required.','Orders','Balance','Support','Settings','Management','New order','Amount (USD)','Payment reference','Credit is added only after your payment is verified by the manager.','Submit payment for review','Payment requests','Transactions','Subject','Message','Send ticket','New password','Confirm password','Save','Confirm order','This amount will be deducted from your balance when you confirm.','Cancel','Confirm and pay','Nothing here yet.','Saved successfully.','The request failed. Please try again.','Check your inbox to confirm your email, then sign in.','If the email is registered, a password reset link will be sent.','Loading…','Payment instructions are not available yet.','Pending','Approved','Rejected','Queued','Processing','Completed','Partial','Cancelled','Needs review','Open','Answered','Closed','Order','Credit','Refund','Order from balance','Sign in to place an order.','This service is currently available by quote only.','Your balance is insufficient.','The price changed. Review the new amount and confirm again.','Enter a valid public link for this platform.','Check the allowed quantity.','The passwords do not match.','Prices and supplier mapping','Service','Price (USD)','Price per','Minimum','Maximum','Available to order','Supplier service ID','Supplier order type','Manual fulfilment','Approve payment','Reject payment','Reply','Users','Block','Unblock','Send to supplier','Sync status','Check the supplier panel before any further action. A previous request may have been received.','Record supplier order','Actual supplier order ID','Supplier catalogue','Supplier connection is not configured.','Allowed quantity','Charge','Publish prices to enable paid orders.','Sign-in failed. Check your email, password and email confirmation.'],
fa:['حساب من','به‌روزرسانی','خروج','پنل حساب در حال اتصال است. فعلاً می‌توانید از بخش بالا درخواست قیمت بفرستید.','ورود','ساخت حساب','بازیابی رمز','ایمیل','رمز عبور','حداقل ۱۲ نویسه وارد کنید. رمز حساب شبکه اجتماعی خود را با کسی به اشتراک نگذارید.','یک حساب برای پیگیری همه سفارش‌ها','سفارش‌ها، موجودی و پشتیبانی را اینجا مدیریت کنید. پیش از ورود، ایمیل خود را تأیید کنید. به رمز حساب شبکه اجتماعی شما نیازی نداریم.','سفارش‌ها','موجودی','پشتیبانی','تنظیمات','مدیریت','سفارش جدید','مبلغ (دلار آمریکا)','شماره پیگیری پرداخت','اعتبار تنها پس از بررسی و تأیید پرداخت توسط مدیر اضافه می‌شود.','ارسال پرداخت برای بررسی','درخواست‌های افزایش اعتبار','تراکنش‌ها','موضوع','پیام','ارسال تیکت','رمز جدید','تکرار رمز','ذخیره','تأیید سفارش','با تأیید شما، این مبلغ از موجودی حسابتان کم می‌شود.','انصراف','تأیید و پرداخت','هنوز موردی ثبت نشده است.','با موفقیت ذخیره شد.','درخواست انجام نشد. دوباره تلاش کنید.','ایمیل تأیید را در صندوق ورودی بررسی کنید و سپس وارد شوید.','اگر این ایمیل ثبت شده باشد، لینک بازیابی رمز ارسال می‌شود.','در حال بارگذاری…','روش پرداخت هنوز تعیین نشده است.','در انتظار','تأییدشده','ردشده','در صف','در حال انجام','تکمیل‌شده','تکمیل جزئی','لغوشده','نیاز به بررسی','باز','پاسخ داده شده','بسته','سفارش','افزایش اعتبار','بازپرداخت','ثبت سفارش با موجودی','برای ثبت سفارش وارد حساب شوید.','این خدمت فعلاً فقط با درخواست قیمت ارائه می‌شود.','موجودی حساب کافی نیست.','قیمت تغییر کرده است. مبلغ جدید را بررسی و دوباره تأیید کنید.','لینک عمومی معتبر همین شبکه را وارد کنید.','تعداد مجاز را بررسی کنید.','رمزها یکسان نیستند.','قیمت‌ها و اتصال تأمین‌کننده','خدمت','قیمت (دلار آمریکا)','قیمت برای هر','حداقل','حداکثر','فعال برای سفارش','شناسه خدمت تأمین‌کننده','نوع سفارش تأمین‌کننده','انجام دستی','تأیید پرداخت','رد پرداخت','پاسخ','کاربران','مسدود کردن','رفع مسدودی','ارسال به تأمین‌کننده','دریافت وضعیت','پیش از هر اقدام، پنل تأمین‌کننده را بررسی کنید؛ ممکن است درخواست قبلی دریافت شده باشد.','ثبت سفارش تأمین‌کننده','شناسه واقعی سفارش تأمین‌کننده','فهرست خدمات تأمین‌کننده','اتصال تأمین‌کننده هنوز تنظیم نشده است.','تعداد مجاز','هزینه','برای فعال‌شدن سفارش‌ها، قیمت‌ها را منتشر کنید.','ورود ناموفق بود. ایمیل، رمز و تأیید ایمیل را بررسی کنید.'],
ar:['حسابي','تحديث','تسجيل الخروج','يجري ربط لوحة الحساب. يمكنك طلب عرض سعر من القسم أعلاه.','تسجيل الدخول','إنشاء حساب','استعادة كلمة المرور','البريد الإلكتروني','كلمة المرور','استخدم 12 حرفاً على الأقل. لا تشارك كلمة مرور حسابك الاجتماعي.','حساب واحد لمتابعة طلباتك','تابع الطلبات والرصيد وتواصل مع الدعم. أكّد بريدك الإلكتروني قبل الدخول. لا نطلب كلمة مرور حسابك الاجتماعي.','الطلبات','الرصيد','الدعم','الإعدادات','الإدارة','طلب جديد','المبلغ (دولار أمريكي)','مرجع الدفع','يُضاف الرصيد بعد التحقق من الدفع واعتماده من المدير فقط.','إرسال الدفع للمراجعة','طلبات إضافة الرصيد','المعاملات','الموضوع','الرسالة','إرسال تذكرة','كلمة المرور الجديدة','تأكيد كلمة المرور','حفظ','تأكيد الطلب','سيُخصم هذا المبلغ من رصيدك عند التأكيد.','إلغاء','تأكيد ودفع','لا توجد سجلات بعد.','تم الحفظ بنجاح.','تعذر تنفيذ الطلب. حاول مجدداً.','تحقق من بريدك لتأكيد عنوانك ثم سجّل الدخول.','إذا كان البريد مسجلاً، سيُرسل رابط الاستعادة.','جارٍ التحميل…','تعليمات الدفع غير متاحة بعد.','قيد الانتظار','معتمد','مرفوض','في قائمة الانتظار','قيد التنفيذ','مكتمل','مكتمل جزئياً','ملغي','يحتاج مراجعة','مفتوحة','تم الرد','مغلقة','طلب','إضافة رصيد','استرداد','الطلب باستخدام الرصيد','سجّل الدخول لإرسال طلب.','هذه الخدمة متاحة حالياً بطلب عرض سعر فقط.','رصيدك غير كافٍ.','تغيّر السعر. راجع المبلغ الجديد وأكّد مجدداً.','أدخل رابطاً عاماً صالحاً لهذه المنصة.','تحقق من الكمية المسموحة.','كلمتا المرور غير متطابقتين.','الأسعار وربط المورّد','الخدمة','السعر (دولار)','السعر لكل','الحد الأدنى','الحد الأقصى','متاح للطلب','معرّف خدمة المورّد','نوع طلب المورّد','تنفيذ يدوي','اعتماد الدفع','رفض الدفع','رد','المستخدمون','حظر','إلغاء الحظر','إرسال إلى المورّد','تحديث الحالة','راجع لوحة المورّد أولاً؛ قد يكون الطلب السابق قد وصل.','تسجيل طلب المورّد','معرّف الطلب الفعلي لدى المورّد','قائمة خدمات المورّد','لم يُضبط اتصال المورّد بعد.','الكمية المسموحة','التكلفة','انشر الأسعار لتفعيل الطلبات المدفوعة.','تعذر الدخول. تحقق من البريد وكلمة المرور وتأكيد البريد.'],
az:['Hesabım','Yenilə','Çıxış','Hesab paneli qoşulur. Hələlik yuxarıdakı bölmədən qiymət təklifi istəyə bilərsiniz.','Daxil ol','Hesab yarat','Şifrəni bərpa et','E-poçt','Şifrə','Ən azı 12 simvol istifadə edin. Sosial hesabınızın şifrəsini paylaşmayın.','Bütün sifarişləriniz bir hesabda','Sifarişləri, balansı və dəstək müraciətlərini izləyin. Girişdən əvvəl e-poçtunuzu təsdiqləyin. Sosial hesabınızın şifrəsini istəmirik.','Sifarişlər','Balans','Dəstək','Parametrlər','İdarəetmə','Yeni sifariş','Məbləğ (ABŞ dolları)','Ödənişin istinad nömrəsi','Balans yalnız ödəniş rəhbər tərəfindən yoxlanıb təsdiqləndikdən sonra artırılır.','Ödənişi yoxlamaya göndər','Balans artırma sorğuları','Əməliyyatlar','Mövzu','Mesaj','Müraciət göndər','Yeni şifrə','Şifrəni təkrar edin','Yadda saxla','Sifarişi təsdiqlə','Təsdiqlədikdə bu məbləğ balansınızdan çıxılacaq.','Ləğv et','Təsdiqlə və ödə','Hələ qeyd yoxdur.','Uğurla yadda saxlanıldı.','Sorğu alınmadı. Yenidən cəhd edin.','E-poçtunuzu təsdiqləmək üçün gələnlər qutusunu yoxlayın, sonra daxil olun.','E-poçt qeydiyyatdadırsa, bərpa linki göndəriləcək.','Yüklənir…','Ödəniş təlimatları hələ hazır deyil.','Gözləmədə','Təsdiqlənib','Rədd edilib','Növbədə','İcra olunur','Tamamlanıb','Qismən tamamlanıb','Ləğv edilib','Yoxlama tələb olunur','Açıq','Cavablandırılıb','Bağlı','Sifariş','Balans artırma','Geri ödəniş','Balansla sifariş et','Sifariş üçün hesabınıza daxil olun.','Bu xidmət hazırda yalnız qiymət sorğusu ilə təqdim olunur.','Balansınız kifayət etmir.','Qiymət dəyişib. Yeni məbləği yoxlayıb yenidən təsdiqləyin.','Bu platformaya aid düzgün açıq link daxil edin.','İcazə verilən miqdarı yoxlayın.','Şifrələr eyni deyil.','Qiymətlər və təchizatçı bağlantısı','Xidmət','Qiymət (ABŞ dolları)','Qiymət vahidi','Minimum','Maksimum','Sifariş üçün aktiv','Təchizatçı xidmətinin ID-si','Təchizatçı sifarişinin növü','Əl ilə icra','Ödənişi təsdiqlə','Ödənişi rədd et','Cavab','İstifadəçilər','Blokla','Bloku aç','Təchizatçıya göndər','Statusu yenilə','Əvvəlcə təchizatçı panelini yoxlayın; əvvəlki sorğu qəbul edilmiş ola bilər.','Təchizatçı sifarişini qeyd et','Təchizatçıdakı real sifariş ID-si','Təchizatçı xidmətləri','Təchizatçı bağlantısı hələ qurulmayıb.','İcazə verilən miqdar','Məbləğ','Ödənişli sifarişlər üçün qiymətləri yayımlayın.','Giriş alınmadı. E-poçtu, şifrəni və e-poçt təsdiqini yoxlayın.'],
tr:['Hesabım','Yenile','Çıkış yap','Hesap paneli bağlanıyor. Şimdilik yukarıdan fiyat teklifi isteyebilirsiniz.','Giriş yap','Hesap oluştur','Şifreyi sıfırla','E-posta','Şifre','En az 12 karakter kullanın. Sosyal hesap şifrenizi paylaşmayın.','Tüm siparişleriniz tek hesapta','Siparişlerinizi, bakiyenizi ve destek taleplerinizi takip edin. Girişten önce e-postanızı doğrulayın. Sosyal hesap şifrenizi istemiyoruz.','Siparişler','Bakiye','Destek','Ayarlar','Yönetim','Yeni sipariş','Tutar (ABD doları)','Ödeme referansı','Bakiye yalnızca ödeme yönetici tarafından doğrulandıktan sonra eklenir.','Ödemeyi incelemeye gönder','Bakiye yükleme talepleri','İşlemler','Konu','Mesaj','Destek talebi gönder','Yeni şifre','Şifreyi doğrula','Kaydet','Siparişi onayla','Onayladığınızda bu tutar bakiyenizden düşülecek.','Vazgeç','Onayla ve öde','Henüz kayıt yok.','Başarıyla kaydedildi.','İstek başarısız oldu. Yeniden deneyin.','E-postanızı doğrulamak için gelen kutunuzu kontrol edin, ardından giriş yapın.','E-posta kayıtlıysa şifre sıfırlama bağlantısı gönderilecektir.','Yükleniyor…','Ödeme talimatları henüz hazır değil.','Bekliyor','Onaylandı','Reddedildi','Sırada','İşleniyor','Tamamlandı','Kısmen tamamlandı','İptal edildi','İnceleme gerekli','Açık','Yanıtlandı','Kapalı','Sipariş','Bakiye yükleme','İade','Bakiyeyle sipariş ver','Sipariş vermek için giriş yapın.','Bu hizmet şu anda yalnızca fiyat teklifiyle sunuluyor.','Bakiyeniz yetersiz.','Fiyat değişti. Yeni tutarı kontrol edip tekrar onaylayın.','Bu platforma ait geçerli, herkese açık bir bağlantı girin.','İzin verilen miktarı kontrol edin.','Şifreler eşleşmiyor.','Fiyatlar ve sağlayıcı eşleştirmesi','Hizmet','Fiyat (ABD doları)','Fiyat birimi','Minimum','Maksimum','Siparişe açık','Sağlayıcı hizmet ID’si','Sağlayıcı sipariş türü','Manuel işlem','Ödemeyi onayla','Ödemeyi reddet','Yanıt','Kullanıcılar','Engelle','Engeli kaldır','Sağlayıcıya gönder','Durumu güncelle','Önce sağlayıcı panelini kontrol edin; önceki istek alınmış olabilir.','Sağlayıcı siparişini kaydet','Gerçek sağlayıcı sipariş ID’si','Sağlayıcı hizmet listesi','Sağlayıcı bağlantısı henüz ayarlanmadı.','İzin verilen miktar','Ücret','Ücretli siparişleri açmak için fiyatları yayınlayın.','Giriş başarısız. E-posta, şifre ve e-posta doğrulamasını kontrol edin.'],
de:['Mein Konto','Aktualisieren','Abmelden','Das Kontosystem wird eingerichtet. Oben können Sie weiterhin ein Angebot anfordern.','Anmelden','Konto erstellen','Passwort zurücksetzen','E-Mail','Passwort','Verwenden Sie mindestens 12 Zeichen. Teilen Sie niemals Ihr Social-Media-Passwort.','Alle Bestellungen in einem Konto','Verwalten Sie Bestellungen, Guthaben und Supportanfragen. Bestätigen Sie vor der Anmeldung Ihre E-Mail. Ihr Social-Media-Passwort wird nicht benötigt.','Bestellungen','Guthaben','Support','Einstellungen','Verwaltung','Neue Bestellung','Betrag (USD)','Zahlungsreferenz','Guthaben wird erst nach Prüfung und Bestätigung der Zahlung durch den Administrator gutgeschrieben.','Zahlung zur Prüfung einreichen','Aufladeanfragen','Transaktionen','Betreff','Nachricht','Ticket senden','Neues Passwort','Passwort bestätigen','Speichern','Bestellung bestätigen','Dieser Betrag wird bei der Bestätigung von Ihrem Guthaben abgebucht.','Abbrechen','Bestätigen und bezahlen','Noch keine Einträge.','Erfolgreich gespeichert.','Die Anfrage ist fehlgeschlagen. Bitte erneut versuchen.','Bestätigen Sie Ihre E-Mail über den Link im Posteingang und melden Sie sich dann an.','Ist diese E-Mail registriert, erhalten Sie einen Link zum Zurücksetzen.','Wird geladen…','Zahlungsanweisungen sind noch nicht verfügbar.','Ausstehend','Bestätigt','Abgelehnt','In der Warteschlange','In Bearbeitung','Abgeschlossen','Teilweise abgeschlossen','Storniert','Prüfung erforderlich','Offen','Beantwortet','Geschlossen','Bestellung','Aufladung','Erstattung','Mit Guthaben bestellen','Melden Sie sich an, um zu bestellen.','Dieser Service ist derzeit nur auf Anfrage erhältlich.','Ihr Guthaben reicht nicht aus.','Der Preis hat sich geändert. Prüfen und bestätigen Sie den neuen Betrag.','Geben Sie einen gültigen öffentlichen Link für diese Plattform ein.','Prüfen Sie die zulässige Menge.','Die Passwörter stimmen nicht überein.','Preise und Anbieterzuordnung','Service','Preis (USD)','Preis pro','Minimum','Maximum','Bestellbar','Service-ID des Anbieters','Bestelltyp des Anbieters','Manuelle Bearbeitung','Zahlung bestätigen','Zahlung ablehnen','Antwort','Nutzer','Sperren','Entsperren','An Anbieter senden','Status abgleichen','Prüfen Sie zuerst das Anbieterpanel; die vorherige Anfrage könnte bereits eingegangen sein.','Anbieterbestellung erfassen','Tatsächliche Bestell-ID beim Anbieter','Anbieterkatalog','Die Anbieteranbindung ist noch nicht eingerichtet.','Zulässige Menge','Kosten','Veröffentlichen Sie Preise, um bezahlte Bestellungen zu aktivieren.','Anmeldung fehlgeschlagen. Prüfen Sie E-Mail, Passwort und E-Mail-Bestätigung.'],
es:['Mi cuenta','Actualizar','Cerrar sesión','Se está conectando el panel. Mientras tanto, puedes solicitar un presupuesto arriba.','Iniciar sesión','Crear cuenta','Restablecer contraseña','Correo electrónico','Contraseña','Usa al menos 12 caracteres. Nunca compartas la contraseña de tu cuenta social.','Todos tus pedidos en una cuenta','Consulta pedidos y saldo y contacta con soporte. Confirma tu correo antes de entrar. No necesitamos la contraseña de tu cuenta social.','Pedidos','Saldo','Soporte','Ajustes','Administración','Nuevo pedido','Importe (USD)','Referencia del pago','El saldo se añade solo después de que el administrador verifique el pago.','Enviar pago para revisión','Solicitudes de recarga','Movimientos','Asunto','Mensaje','Enviar consulta','Nueva contraseña','Confirmar contraseña','Guardar','Confirmar pedido','Este importe se descontará de tu saldo al confirmar.','Cancelar','Confirmar y pagar','Todavía no hay registros.','Guardado correctamente.','La solicitud falló. Inténtalo de nuevo.','Revisa tu bandeja de entrada para confirmar el correo y luego inicia sesión.','Si el correo está registrado, enviaremos un enlace de recuperación.','Cargando…','Las instrucciones de pago aún no están disponibles.','Pendiente','Aprobado','Rechazado','En cola','En proceso','Completado','Parcial','Cancelado','Requiere revisión','Abierta','Respondida','Cerrada','Pedido','Recarga','Reembolso','Pedir con el saldo','Inicia sesión para hacer un pedido.','Este servicio está disponible por presupuesto, de momento.','Tu saldo es insuficiente.','El precio cambió. Revisa el nuevo importe y confirma de nuevo.','Introduce un enlace público válido de esta plataforma.','Comprueba la cantidad permitida.','Las contraseñas no coinciden.','Precios y conexión del proveedor','Servicio','Precio (USD)','Precio por','Mínimo','Máximo','Disponible para pedidos','ID del servicio del proveedor','Tipo de pedido del proveedor','Gestión manual','Aprobar pago','Rechazar pago','Respuesta','Usuarios','Bloquear','Desbloquear','Enviar al proveedor','Actualizar estado','Consulta primero el panel del proveedor; la solicitud anterior podría haberse recibido.','Registrar pedido del proveedor','ID real del pedido del proveedor','Catálogo del proveedor','La conexión del proveedor aún no está configurada.','Cantidad permitida','Coste','Publica precios para activar los pedidos de pago.','No se pudo iniciar sesión. Comprueba correo, contraseña y confirmación del correo.'],
fr:['Mon compte','Actualiser','Se déconnecter','Le compte est en cours de connexion. Vous pouvez demander un devis dans la section ci-dessus.','Se connecter','Créer un compte','Réinitialiser le mot de passe','E-mail','Mot de passe','Utilisez au moins 12 caractères. Ne partagez jamais le mot de passe de votre réseau social.','Toutes vos commandes dans un compte','Suivez vos commandes et votre solde et contactez le support. Confirmez votre e-mail avant de vous connecter. Le mot de passe de votre réseau social est inutile.','Commandes','Solde','Support','Paramètres','Gestion','Nouvelle commande','Montant (USD)','Référence du paiement','Le solde est crédité uniquement après vérification du paiement par le gestionnaire.','Soumettre le paiement','Demandes de crédit','Transactions','Objet','Message','Envoyer un ticket','Nouveau mot de passe','Confirmer le mot de passe','Enregistrer','Confirmer la commande','Ce montant sera déduit de votre solde à la confirmation.','Annuler','Confirmer et payer','Aucun élément pour le moment.','Enregistrement réussi.','La demande a échoué. Veuillez réessayer.','Confirmez votre adresse via l’e-mail reçu, puis connectez-vous.','Si cette adresse est enregistrée, un lien de réinitialisation sera envoyé.','Chargement…','Les instructions de paiement ne sont pas encore disponibles.','En attente','Approuvé','Refusé','En file d’attente','En cours','Terminé','Partiel','Annulé','À vérifier','Ouvert','Répondu','Fermé','Commande','Crédit','Remboursement','Commander avec le solde','Connectez-vous pour passer commande.','Ce service est actuellement disponible sur devis uniquement.','Votre solde est insuffisant.','Le prix a changé. Vérifiez le nouveau montant et confirmez à nouveau.','Saisissez un lien public valide pour cette plateforme.','Vérifiez la quantité autorisée.','Les mots de passe ne correspondent pas.','Tarifs et connexion du fournisseur','Service','Prix (USD)','Prix pour','Minimum','Maximum','Disponible à la commande','ID du service fournisseur','Type de commande fournisseur','Traitement manuel','Approuver le paiement','Refuser le paiement','Réponse','Utilisateurs','Bloquer','Débloquer','Envoyer au fournisseur','Actualiser le statut','Vérifiez d’abord le panneau du fournisseur ; la demande précédente a peut-être été reçue.','Enregistrer la commande fournisseur','ID réel de la commande fournisseur','Catalogue du fournisseur','La connexion au fournisseur n’est pas encore configurée.','Quantité autorisée','Coût','Publiez les tarifs pour activer les commandes payantes.','Échec de connexion. Vérifiez l’e-mail, le mot de passe et la confirmation de l’adresse.'],
ru:['Мой аккаунт','Обновить','Выйти','Панель аккаунта подключается. Пока можно запросить цену в разделе выше.','Войти','Создать аккаунт','Восстановить пароль','Электронная почта','Пароль','Используйте не менее 12 символов. Не сообщайте пароль от социальной сети.','Все заказы в одном аккаунте','Следите за заказами и балансом, обращайтесь в поддержку. Подтвердите почту перед входом. Пароль от социальной сети не нужен.','Заказы','Баланс','Поддержка','Настройки','Управление','Новый заказ','Сумма (USD)','Номер платежа','Средства зачисляются только после проверки платежа администратором.','Отправить платёж на проверку','Заявки на пополнение','Операции','Тема','Сообщение','Отправить обращение','Новый пароль','Подтвердите пароль','Сохранить','Подтвердить заказ','При подтверждении эта сумма будет списана с вашего баланса.','Отмена','Подтвердить и оплатить','Записей пока нет.','Успешно сохранено.','Запрос не выполнен. Повторите попытку.','Подтвердите адрес по письму, затем войдите.','Если адрес зарегистрирован, будет отправлена ссылка для восстановления.','Загрузка…','Инструкции по оплате пока недоступны.','Ожидает проверки','Одобрено','Отклонено','В очереди','Выполняется','Завершено','Частично выполнено','Отменено','Требует проверки','Открыто','Есть ответ','Закрыто','Заказ','Пополнение','Возврат','Заказать с баланса','Войдите, чтобы оформить заказ.','Эта услуга пока доступна только по запросу цены.','Недостаточно средств на балансе.','Цена изменилась. Проверьте новую сумму и подтвердите ещё раз.','Укажите действующую публичную ссылку этой платформы.','Проверьте допустимое количество.','Пароли не совпадают.','Цены и подключение поставщика','Услуга','Цена (USD)','Цена за','Минимум','Максимум','Доступно для заказа','ID услуги поставщика','Тип заказа поставщика','Ручное выполнение','Одобрить платёж','Отклонить платёж','Ответ','Пользователи','Заблокировать','Разблокировать','Отправить поставщику','Обновить статус','Сначала проверьте панель поставщика: предыдущий запрос мог быть получен.','Записать заказ поставщика','Фактический ID заказа поставщика','Каталог поставщика','Подключение поставщика ещё не настроено.','Допустимое количество','Стоимость','Опубликуйте цены для включения платных заказов.','Не удалось войти. Проверьте почту, пароль и подтверждение адреса.'],
'zh-CN':['我的账户','刷新','退出登录','账户面板正在连接。您仍可在上方申请报价。','登录','创建账户','重置密码','电子邮箱','密码','请使用至少12个字符。请勿分享社交账户密码。','一个账户，管理全部订单','查看订单与余额并联系支持。请在登录前验证邮箱。我们不需要您的社交账户密码。','订单','余额','支持','设置','管理','新订单','金额（美元）','付款参考号','管理员核实付款后，才会增加余额。','提交付款审核','充值申请','交易记录','主题','消息','提交工单','新密码','确认密码','保存','确认订单','确认后，该金额将从您的余额中扣除。','取消','确认并支付','暂无记录。','保存成功。','请求失败，请重试。','请查看收件箱并验证邮箱，然后登录。','如果该邮箱已注册，我们将发送密码重置链接。','加载中…','付款说明尚未提供。','待审核','已批准','已拒绝','排队中','处理中','已完成','部分完成','已取消','需要审核','待处理','已回复','已关闭','订单','充值','退款','使用余额下单','请登录后下单。','此服务目前仅支持申请报价。','余额不足。','价格已变更。请核对新金额并重新确认。','请输入此平台的有效公开链接。','请检查允许的数量。','两次输入的密码不一致。','价格与供应商配置','服务','价格（美元）','计价单位','最小数量','最大数量','允许下单','供应商服务编号','供应商订单类型','手动处理','批准付款','拒绝付款','回复','用户','封禁','解封','发送给供应商','同步状态','请先检查供应商面板，之前的请求可能已被接收。','记录供应商订单','实际供应商订单编号','供应商服务目录','尚未配置供应商连接。','允许的数量','费用','发布价格后即可启用付费订单。','登录失败。请检查邮箱、密码及邮箱验证状态。']};
const translations=Object.fromEntries(Object.entries(packs).map(([lang,values])=>[lang,Object.fromEntries(keys.map((key,i)=>[key,values[i]]))]));
const quantityLabels={en:'Quantity',fa:'تعداد',ar:'الكمية',az:'Miqdar',tr:'Miktar',de:'Menge',es:'Cantidad',fr:'Quantité',ru:'Количество','zh-CN':'数量'};for(const [locale,label] of Object.entries(quantityLabels))translations[locale].quantity=label;
const notReceived={en:'I checked the supplier panel: no order was created. Release for manual review.',fa:'پنل تأمین‌کننده را بررسی کردم: سفارشی ثبت نشده است. آزادسازی برای رسیدگی دستی.',ar:'راجعت لوحة المورّد: لم يُنشأ طلب. إتاحة المعالجة اليدوية.',az:'Təchizatçı panelini yoxladım: sifariş yaradılmayıb. Əl ilə baxışa burax.',tr:'Sağlayıcı panelini kontrol ettim: sipariş oluşmadı. Manuel incelemeye aç.',de:'Anbieterpanel geprüft: Keine Bestellung erstellt. Zur manuellen Bearbeitung freigeben.',es:'He revisado el proveedor: no se creó un pedido. Liberar para revisión manual.',fr:'Panneau du fournisseur vérifié : aucune commande créée. Autoriser le traitement manuel.',ru:'Панель поставщика проверена: заказ не создан. Передать на ручную проверку.','zh-CN':'我已检查供应商面板：未创建订单。转为人工处理。'};for(const [locale,label] of Object.entries(notReceived))translations[locale].notReceived=label;
const authFragment=new URLSearchParams(location.hash.slice(1));if(authFragment.has('access_token')||authFragment.has('refresh_token'))history.replaceState(null,'',location.pathname+location.search+'#account');
let lang='en',ready=false,state=null,adminState=null,authMode='login',tab='orders',catalog=[],busy=false,pendingOrder=null,nonce=null,noncePayload='',queue=Promise.resolve();
const t=key=>translations[lang]?.[key]||translations.en[key]||key;
const money=v=>new Intl.NumberFormat(lang,{style:'currency',currency:'USD'}).format(Number(v)/100);
const labelService=id=>window.seraySocial?.label(id)||id;
const localDate=v=>new Date(v).toLocaleString(lang);
function status(key,error=false){$('sp-status').textContent=key?t(key):'';$('sp-status').dataset.error=String(error);}
function err(e){const key={LOGIN_FAILED:'signinError',VERIFY_EMAIL:'verify',INSUFFICIENT_BALANCE:'insufficient',PRICE_CHANGED:'priceChanged',INVALID_LINK:'invalidLink',INVALID_QUANTITY:'invalidQuantity',SERVICE_UNAVAILABLE:'unavailable',PAYMENT_NOT_CONFIGURED:'paymentMissing',PROVIDER_NOT_CONFIGURED:'providerMissing',PROVIDER_REVIEW_REQUIRED:'providerReview',SETUP_REQUIRED:'setup',PASSWORD_MISMATCH:'passwordMismatch'}[e.code]||'failed';status(key,true);if(e.code==='LOGIN_REQUIRED'){state=null;render();status('loginFirst',true);}return key;}
async function api(action,payload={}){
 const operation=async()=>{const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),25000);try{const r=await fetch(endpoint,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...payload}),signal:controller.signal});const data=await r.json();if(!r.ok){const e=new Error(data.error||'FAILED');e.code=data.error;throw e;}return data;}finally{clearTimeout(timer);}};
 const p=queue.then(operation);queue=p.catch(()=>{});return p;
}
async function run(button,work){if(busy)return;busy=true;if(button)button.disabled=true;status('loading');try{await work();}catch(e){err(e);}finally{busy=false;if(button)button.disabled=false;updatePaid();}}
function element(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function button(key,fn){const b=element('button',t(key));b.type='button';b.addEventListener('click',()=>run(b,fn));return b;}
function empty(list){list.append(element('p',t('empty')));}
function card(list,title,lines=[],tag){const c=element('article',undefined,'sp-item');c.append(element('h4',title));if(tag)c.append(element('span',t(tag),'sp-tag'));for(const line of lines)c.append(element('p',line));list.append(c);return c;}
function list(id,rows,fn){const root=$(id);root.replaceChildren();if(!rows.length)empty(root);else rows.forEach(r=>fn(root,r));}
function authTab(mode){authMode=mode;document.querySelectorAll('[data-auth-tab]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.authTab===mode)));$('sp-password-field').hidden=mode==='recover';$('sp-password').disabled=mode==='recover';$('sp-password').autocomplete=mode==='signup'?'new-password':'current-password';$('sp-password-note').hidden=mode==='recover';$('sp-auth-submit').textContent=t(mode);}
function switchTab(name){tab=name;document.querySelectorAll('[data-sp-tab]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.spTab===name)));document.querySelectorAll('[data-sp-view]').forEach(v=>v.hidden=v.dataset.spView!==name);if(name==='admin'&&!adminState)run(null,async()=>{adminState=await api('admin');renderAdmin();status('');});}
function render(){
 $('sp-setup').hidden=ready;$('sp-auth').hidden=!ready||Boolean(state);$('sp-dashboard').hidden=!state;$('sp-user-actions').hidden=!state;authTab(authMode);
 if(!state){updatePaid();return;}
 $('sp-email-label').textContent=state.user.email;$('sp-admin-tab').hidden=!state.user.isAdmin;if(tab==='admin'&&!state.user.isAdmin)tab='orders';
 $('sp-balance').textContent=money(state.wallet.balance_minor);$('sp-payment').textContent=state.paymentInstructions||t('paymentMissing');$('sp-topup-form').hidden=!state.paymentInstructions;
 list('sp-orders',state.orders,(root,o)=>card(root,labelService(o.service_id),[o.id,localDate(o.created_at),o.link,t('quantity')+': '+new Intl.NumberFormat(lang).format(o.quantity),t('charge')+': '+money(o.charge_minor)+(o.refunded_minor?' · '+t('refund')+': '+money(o.refunded_minor):'')],o.status));
 list('sp-topups',state.topups,(root,o)=>card(root,money(o.amount_minor),[o.reference,localDate(o.created_at)],o.status));
 list('sp-transactions',state.transactions,(root,o)=>card(root,(o.amount_minor>0?'+':'')+money(o.amount_minor),[localDate(o.created_at)],o.kind));
 list('sp-tickets',state.tickets,(root,o)=>card(root,o.subject,[o.message,...(o.reply?[t('reply')+': '+o.reply]:[]),localDate(o.created_at)],o.status));
 switchTab(tab);if(adminState)renderAdmin();updatePaid();
}
async function refresh(){state=await api('dashboard');adminState=null;render();}
function translate(){const selected=window.__sdgLanguage||document.documentElement.lang;lang=translations[selected]?selected:'en';document.querySelectorAll('[data-sp]').forEach(e=>e.textContent=t(e.dataset.sp));render();}
// Admin controls are created with textContent. User text is never injected as HTML.
function adminSection(title){const details=element('details'),summary=element('summary',t(title)),root=element('div',undefined,'sp-list');details.append(summary,root);$('sp-admin').append(details);return root;}
function inputLabel(form,key,type='text',value='',options){const label=element('label'),input=element(options?'select':'input');label.append(element('span',t(key)));if(options){for(const [v,name] of options)input.add(new Option(name,v));}else input.type=type;if(options&&value==='')input.selectedIndex=0;else input.value=value;label.append(input);form.append(label);return input;}
async function adminRefresh(){adminState=await api('admin');state=await api('dashboard');render();status('done');}
function renderAdmin(){
 if(!adminState||!state?.user.isAdmin)return;const opened=[...$('sp-admin').querySelectorAll('details[open]')].map(d=>d.firstElementChild.textContent);$('sp-admin').replaceChildren();
 const prices=adminSection('rates'),form=element('form'),choice=inputLabel(form,'service','text','',adminState.services.map(s=>[s.id,labelService(s.id)]));
 const fields=element('div',undefined,'sp-mini-grid');form.append(fields);
 const rate=inputLabel(fields,'rate','number'),unit=inputLabel(fields,'unit','text','1000',[['1000','1000'],['1','1']]),min=inputLabel(fields,'min','number'),max=inputLabel(fields,'max','number'),type=inputLabel(fields,'providerType','text','manual',[['manual',t('manual')],['Default','Default'],['Custom Comments','Custom Comments']]),providerId=inputLabel(fields,'providerId','number');
 rate.step='.01';rate.min='.01';rate.max='1000000';min.min='1';max.min='1';min.max=max.max='1000000';providerId.min='1';
 const enabledLabel=element('label',undefined,'sp-check'),enabled=element('input');enabled.type='checkbox';enabledLabel.append(enabled,element('span',t('enabled')));form.append(enabledLabel);
 const save=element('button',t('save'),'sp-primary');save.type='submit';form.append(save);prices.append(form);
 const load=()=>{const s=adminState.services.find(s=>s.id===choice.value);rate.value=s.rate_minor?Number(s.rate_minor)/100:'';unit.value=String(s.pricing_unit);min.value=s.min_quantity;max.value=s.max_quantity;type.value=s.provider_type;providerId.value=s.provider_service_id||'';enabled.checked=s.enabled;providerId.disabled=type.value==='manual';};load();choice.addEventListener('change',load);type.addEventListener('change',()=>providerId.disabled=type.value==='manual');
 form.addEventListener('submit',e=>{e.preventDefault();run(save,async()=>{await api('price',{id:choice.value,rateMinor:rate.value?Math.round(Number(rate.value)*100):null,unit:Number(unit.value),min:Number(min.value),max:Number(max.value),enabled:enabled.checked,providerType:type.value,providerId:Number(providerId.value)});catalog=(await api('catalog')).services;const selected=choice.value;await adminRefresh();const next=$('sp-admin').querySelector('select');if(next){next.value=selected;next.dispatchEvent(new Event('change'));}});});
 prices.append(button('providerCatalog',async()=>{const result=await api('providerCatalog');let root=prices.querySelector('[data-provider-list]');if(!root){root=element('div',undefined,'sp-list');root.dataset.providerList='';prices.append(root);}root.replaceChildren();result.services.forEach(s=>card(root,String(s.service)+' · '+s.name,[s.category,String(s.rate)+' / 1000',String(s.min)+'–'+String(s.max),s.type]));status('');}));
 const topups=adminSection('topups');if(!adminState.topups.length)empty(topups);
 adminState.topups.forEach(o=>{const c=card(topups,money(o.amount_minor),[o.user_id,o.reference,localDate(o.created_at)]),actions=element('div',undefined,'sp-actions');actions.append(button('approve',async()=>{await api('approve',{id:o.id,approve:true});await adminRefresh();}),button('reject',async()=>{await api('approve',{id:o.id,approve:false});await adminRefresh();}));c.append(actions);});
 const orders=adminSection('orders');if(!adminState.orders.length)empty(orders);
 adminState.orders.forEach(o=>{const c=card(orders,labelService(o.service_id),[o.id,o.user_id,o.link,new Intl.NumberFormat(lang).format(o.quantity)+' · '+money(o.charge_minor),JSON.stringify(o.details)],o.status);
  if(['completed','partial','cancelled'].includes(o.status))return;
  if(['submitting','unknown'].includes(o.provider_state)){c.append(element('p',t('providerReview')));const f=element('form'),id=inputLabel(f,'providerActualId','number');id.required=true;id.min='1';const b=element('button',t('reconcile'));f.append(b);f.addEventListener('submit',e=>{e.preventDefault();run(b,async()=>{await api('reconcile',{id:o.id,providerId:Number(id.value)});await adminRefresh();});});c.append(f);const release=element('form'),checked=element('input'),label=element('label',undefined,'sp-check');checked.type='checkbox';checked.required=true;label.append(checked,element('span',t('notReceived')));const rb=element('button',t('save'));release.append(label,rb);release.addEventListener('submit',e=>{e.preventDefault();if(!checked.checked)return;run(rb,async()=>{await api('reconcile',{id:o.id,confirmedNotReceived:true});await adminRefresh();});});c.append(release);return;}
  const actions=element('div',undefined,'sp-actions');c.append(actions);
  if(o.provider_state==='submitted'){actions.append(button('sync',async()=>{await api('sync',{id:o.id});await adminRefresh();}));return;}
  if(o.provider_type!=='manual'&&adminState.providerReady)actions.append(button('sendProvider',async()=>{try{await api('dispatch',{id:o.id});}finally{adminState=null;await refresh();adminState=await api('admin');renderAdmin();}status('done');}));
  const f=element('form'),select=inputLabel(f,'orders','text',o.status,['queued','processing','completed','partial','cancelled','needs_review'].map(v=>[v,t(v)])),refund=inputLabel(f,'refund','number',Number(o.refunded_minor)/100);refund.min=Number(o.refunded_minor)/100;refund.max=Number(o.charge_minor)/100;refund.step='.01';const b=element('button',t('save'));f.append(b);f.addEventListener('submit',e=>{e.preventDefault();run(b,async()=>{await api('orderStatus',{id:o.id,status:select.value,refundMinor:Math.round(Number(refund.value)*100)});await adminRefresh();});});c.append(f);
 });
 const tickets=adminSection('support');if(!adminState.tickets.length)empty(tickets);adminState.tickets.forEach(o=>{const c=card(tickets,o.subject,[o.user_id,o.message,o.reply],o.status),f=element('form'),label=element('label'),reply=element('textarea');label.append(element('span',t('reply')),reply);reply.value=o.reply;reply.required=true;reply.maxLength=4000;const b=element('button',t('sendTicket'));f.append(label,b);c.append(f);f.addEventListener('submit',e=>{e.preventDefault();run(b,async()=>{await api('reply',{id:o.id,reply:reply.value});await adminRefresh();});});});
 const users=adminSection('users');adminState.users.forEach(u=>{const c=card(users,u.email,[u.user_id]);if(u.user_id!==state.user.id)c.append(button(u.blocked?'unblock':'block',async()=>{await api('block',{id:u.user_id,blocked:!u.blocked});await adminRefresh();}));});
 $('sp-admin').querySelectorAll('details').forEach(d=>d.open=opened.includes(d.firstElementChild.textContent));
}
function selection(){return window.seraySocial?.read();}
function cost(s,q){return Math.ceil(Number(s.rate_minor)*q/s.pricing_unit);}
function updatePaid(){const data=selection(),s=catalog.find(s=>s.id===data?.serviceId),b=$('sp-paid-button');if(!b)return;$('sp-paid').hidden=!ready;b.disabled=busy;const hint=$('sp-paid-hint');if(!s){hint.textContent=t('unavailable');b.disabled=true;}else{const quantity=data.quantity;hint.textContent=money(s.rate_minor)+' / '+s.pricing_unit+' · '+t('range')+': '+s.min_quantity+'–'+s.max_quantity+(Number.isSafeInteger(quantity)&&quantity>0?' · '+t('charge')+': '+money(cost(s,quantity)):'');}b.textContent=t('paidOrder');}
$('sp-paid-button')?.addEventListener('click',()=>{
 if(!state){status('loginFirst');$('account').scrollIntoView({behavior:'smooth',block:'start'});return;}
 if(!window.seraySocial?.validate(false))return;
 const d=selection(),s=catalog.find(s=>s.id===d?.serviceId);if(!s)return;
 if(!Number.isSafeInteger(d.quantity)||d.quantity<s.min_quantity||d.quantity>s.max_quantity){status('invalidQuantity',true);$('account').scrollIntoView({block:'start'});return;}
 const charge=cost(s,d.quantity);if(charge>Number(state.wallet.balance_minor)){switchTab('wallet');status('insufficient',true);$('account').scrollIntoView({block:'start'});return;}
 const signature=JSON.stringify(d);if(signature!==noncePayload||!nonce){nonce=crypto.randomUUID();noncePayload=signature;}
 pendingOrder={...d,expectedCharge:charge,requestKey:nonce};$('sp-confirm-summary').textContent=labelService(d.serviceId)+' · '+new Intl.NumberFormat(lang).format(d.quantity)+'\n'+d.link;$('sp-confirm-price').textContent=money(charge);$('sp-confirm').showModal();
});
$('sp-confirm-cancel').addEventListener('click',()=>$('sp-confirm').close());
$('sp-confirm-pay').addEventListener('click',()=>run($('sp-confirm-pay'),async()=>{if(!pendingOrder)return;try{await api('order',pendingOrder);nonce=null;noncePayload='';pendingOrder=null;$('sp-confirm').close();tab='orders';await refresh();status('done');$('account').scrollIntoView({block:'start'});}catch(e){$('sp-confirm').close();if(e.code==='PRICE_CHANGED')catalog=(await api('catalog')).services;throw e;}}));
$('sp-auth-form').addEventListener('submit',e=>{e.preventDefault();run($('sp-auth-submit'),async()=>{const result=await api(authMode,{email:$('sp-email').value,password:$('sp-password').value});$('sp-password').value='';if(authMode==='recover')status('resetSent');else if(authMode==='signup'&&result.checkEmail)status('verify');else{await refresh();status('');}});});
$('sp-logout').addEventListener('click',()=>run($('sp-logout'),async()=>{await api('logout');state=null;adminState=null;pendingOrder=null;nonce=null;noncePayload='';render();status('');}));
$('sp-refresh').addEventListener('click',()=>run($('sp-refresh'),async()=>{catalog=(await api('catalog')).services;await refresh();status('');}));
$('sp-topup-form').addEventListener('submit',e=>{e.preventDefault();run(e.submitter,async()=>{await api('topup',{amountMinor:Math.round(Number($('sp-topup-amount').value)*100),reference:$('sp-topup-reference').value});e.target.reset();await refresh();status('done');});});
$('sp-ticket-form').addEventListener('submit',e=>{e.preventDefault();run(e.submitter,async()=>{await api('ticket',{subject:$('sp-ticket-subject').value,message:$('sp-ticket-message').value});e.target.reset();await refresh();status('done');});});
$('sp-password-form').addEventListener('submit',e=>{e.preventDefault();run(e.submitter,async()=>{if($('sp-new-password').value!==$('sp-repeat-password').value){const error=new Error();error.code='PASSWORD_MISMATCH';throw error;}await api('password',{password:$('sp-new-password').value});e.target.reset();status('done');});});
// Accessible tabs: roving focus, arrows, Home and End.
function tabs(selector,onChange){const nodes=[...document.querySelectorAll(selector)];nodes.forEach(b=>{b.setAttribute('role','tab');b.tabIndex=b.getAttribute('aria-selected')==='true'?0:-1;b.addEventListener('click',()=>{onChange(b);nodes.forEach(x=>x.tabIndex=x===b?0:-1);});b.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const visible=nodes.filter(x=>!x.hidden),i=visible.indexOf(b);const next=visible[e.key==='Home'?0:e.key==='End'?visible.length-1:(i+(e.key==='ArrowRight'?1:-1)+visible.length)%visible.length];next.focus();next.click();});});}
tabs('[data-auth-tab]',b=>authTab(b.dataset.authTab));tabs('[data-sp-tab]',b=>switchTab(b.dataset.spTab));
document.querySelectorAll('.flag-button').forEach(b=>b.addEventListener('click',()=>queueMicrotask(translate)));
document.addEventListener('seray:selection',updatePaid);translate();
async function boot(){
 try{const r=await fetch(endpoint,{credentials:'include',cache:'no-store'});if(!r.ok)return;const config=await r.json();ready=config.ready===true;if(!ready)return;
  const fragment=authFragment;const access=fragment.get('access_token'),refreshToken=fragment.get('refresh_token'),recovery=fragment.get('type')==='recovery';
  if(access&&refreshToken){history.replaceState(null,'',location.pathname+location.search+'#account');await api('session',{access_token:access,refresh_token:refreshToken});if(recovery)tab='settings';}
  catalog=(await api('catalog')).services;
  try{await refresh();}catch(e){if(e.code!=='LOGIN_REQUIRED')throw e;state=null;}
  render();if(access)$('account').scrollIntoView({block:'start'});
 }catch(e){err(e);render();}
}
boot();
// Public QA metadata contains UI strings only, not account data or tokens.
window.serayPanelTranslations=translations;
})();
